In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Base Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative indexing", arr[-3])

Base Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative indexing 8


In [3]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],    
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 1])
print("Entire row", arr_2d[0])
print("Entire col", arr_2d[:,1])

Specific element 5
Entire row [1 2 3]
Entire col [2 5 8]


In [4]:
unsorted = np.array([7, 4, 9, 3, 2, 6, 0, 10, 1])
print("Sorted array", np.sort(unsorted))

Sorted array [ 0  1  2  3  4  6  7  9 10]


In [5]:
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2d array by col", np.sort(arr_2d_unsorted, axis=0))

Sorted 2d array by col [[1 1]
 [2 2]
 [3 3]]


Filter

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers", even_number)

Even numbers [ 2  4  6  8 10]


Filter with Mask

In [7]:
mask = numbers > 5
print("Numbers greater than 5 ", numbers[mask])

Numbers greater than 5  [ 6  7  8  9 10]


Fancy indexing vs np.where()

In [8]:
indices = [0, 6, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print(where_result)
print("NP where ", numbers[where_result])

[1 7 5]
(array([5, 6, 7, 8, 9]),)
NP where  [ 6  7  8  9 10]


In [9]:
condition_array = np.where(numbers > 5, numbers*3, numbers)
print(condition_array)

[ 1  2  3  4  5 18 21 24 27 30]


the code above is short way of writing the code given below

In [10]:
if(numbers > 5){
    numbers * 4
} else{
    numbers
}

SyntaxError: invalid syntax (3754263853.py, line 1)

In [11]:
condition_array = np.where(numbers > 5, "True", "False")
print(condition_array)

['False' 'False' 'False' 'False' 'False' 'True' 'True' 'True' 'True'
 'True']


Adding and Removing data

In [14]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


Array compatibility

In [17]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9, 44])

print("Compatibility Shapes", a.shape == b.shape == c.shape)

Compatibility Shapes False


In [20]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([5, 6])

with_new_row = np.vstack((original, new_row))

print(original)
print(with_new_row)

new_col = np.array([[7],[8]])
with_new_col = np.hstack((original, new_col))
print(with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [21]:
arr = np.array([1, 2, 3,4 ,5])
deleted = np.delete(arr, 2)
print("Array after deletion: ", deleted)

Array after deletion:  [1 2 4 5]
