##Basics about numpy

In [4]:
import numpy as np

In [5]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: " ,arr_1d)

arr_2d = np.array([[1,2, 3,], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


List VS Numpy array

In [8]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)

np_array = np.array([1, 2, 3])
print("python array multiplication", np_array * 2)

import time 
start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
python array multiplication [2 4 6]

 List operation time:  0.10308623313903809

 Numpy operation time:  0.008586883544921875


Creating array form scratch

In [9]:
zeros = np.zeros((3, 4))
print("zeros array: \n", zeros)

zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
ones = np.ones((3, 4))
print("ones array: \n", ones)

full = np.full((2, 2), 9)
print("full array: \n", full)

ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array: 
 [[9 9]
 [9 9]]


In [14]:
random  = np.random.random((2, 3))
print("random array: \n", random)

sequence = np.arange(0, 113, 2)
print("sequence array: \n", sequence)

random array: 
 [[0.54767541 0.88981434 0.30501752]
 [0.04754683 0.13091603 0.66560012]]
sequence array: 
 [  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112]


Vector Matrix and Tensor

In [17]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Array Properties

In [18]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Dtype:  int64


Array reshaping

In [22]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array ", reshaped)

flattened = arr.flatten()
print("flattened array ", flattened)

raveled = arr.ravel()
print("raveled array ", raveled)

transpose = reshaped.T
print("\n Transposed array ", transpose)


Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
